package:
  name: pykerberos
  version: 1.1.10

source:
  fn: pykerberos-1.1.10.tar.gz
  url: https://pypi.python.org/packages/source/p/pykerberos/pykerberos-1.1.10.tar.gz
  md5: 9f18109b73e3f42eba0b70c18073883f

build:
  number: 1           [osx]
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools
    - krb5
  run:
    - python
    - krb5

test:
  imports:
    - kerberos

about:
  home: https://github.com/02strich/pykerberos
  license: Apache
  license_file: LICENSE
  summary: high-level interface to Kerberos
  description: |
    pykerberos is a high-level wrapper for Kerberos (GSSAPI) operations. The goal is to
    avoid having to build a module that wraps the entire Kerberos.framework
    and instead offer a limited set of functions that do what is needed for
    client/server Kerberos authentication.
  doc_url: https://pypi.python.org/pypi/kerberos
  doc_source_url: https://github.com/apple/ccs-pykerberos/blob/master/README.rst
