package:
  name: babel
  version: 2.4.0

source:
  fn: Babel-2.4.0.tar.gz
  url: https://pypi.python.org/packages/92/22/643f3b75f75e0220c5ef9f5b72b619ccffe9266170143a4821d4885198de/Babel-2.4.0.tar.gz
  md5: 90e7a0add19b2036a9b415630a0d9388

build:
  entry_points:
    - pybabel = babel.messages.frontend:main

requirements:
  build:
    - python
    - setuptools
    - pytz
  run:
    - python
    - pytz

test:
  commands:
    - pybabel -h
  imports:
    - babel
    - babel.messages
    - babel.localtime

about:
  home: http://babel.pocoo.org/
  license: BSD
  license_file: LICENSE
  summary: Utilities to internationalize and localize Python applications
  description: |
    Babel is an integrated collection of utilities that assist in
    internationalizing and localizing Python applications, with an emphasis
    on web-base applications.
  doc_url: http://babel.pocoo.org/en/latest/#user-documentation
  doc_source_url: https://github.com/python-babel/babel/blob/master/docs/index.rst
  dev_url: https://github.com/python-babel/babel
