package:
  name: appdirs
  version: 1.4.0

source:
  fn: appdirs-1.4.0.tar.gz
  url: https://pypi.io/packages/source/a/appdirs/appdirs-1.4.0.tar.gz
  md5: 1d17b4c9694ab84794e228f28dc3275b

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - appdirs

about:
  home: http://github.com/ActiveState/appdirs
  license: MIT
  summary: Python module for determining appropriate platform-specific dirs
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/ActiveState/appdirs
  doc_url: https://github.com/ActiveState/appdirs
