package:
  name: pygpu
  version: "0.6.8"

source:
  git_url: https://github.com/Theano/libgpuarray.git
  git_tag: v0.6.8

build:
  number:  0
  detect_binary_files_with_prefix: False

requirements:
  build:
    - m2-git         [win]
    - m2-filesystem  [win]
    - git            [not win and not ppc64le]
    - python
    - cython
    - numpy
    - mako
    - libgpuarray ==0.6.8
    - setuptools
  run:
    - python
    - libgpuarray ==0.6.8
    - numpy
    - mako
    - nose
    - six

about:
  license: BSD
