package:
  name: holoviews
  version: 1.7.0

source:
  git_url: https://github.com/ioam/holoviews.git
  git_tag: v1.7.0

requirements:
  build:
    - python
  run:
    - python
    - param >=1.5,<2.0
    - numpy
    - ipykernel            [py3k]

test:
  imports:
    - holoviews

about:
  home: http://holoviews.org/
  license: BSD
  license_file: LICENSE.txt
  summary: Analyze and visualize scientific or engineering data
  description: |
    HoloViews is a Python library that makes analyzing and visualizing
    scientific or engineering data much simpler, more intuitive, and more
    easily reproducible.
  doc_url: http://holoviews.org/
  dev_url: https://github.com/ioam/holoviews
