package:
  name: natsort
  version: 5.0.3

source:
  fn: natsort-5.0.3.tar.gz
  url: https://pypi.python.org/packages/8e/6b/a4e3031e573ef29a251984ac0a6bd26cedac6f5e67a7607c9746bd64b3fe/natsort-5.0.3.tar.gz
  md5: 885997c444be12030960e65203a9ac10

build:
  entry_points:
    - natsort = natsort.__main__:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - natsort

about:
  home: https://github.com/SethMMorton/natsort
  license: MIT
  license_file: LICENSE
  summary: Sort lists naturally
  description: |
    natsort provides a function natsorted that helps sort lists "naturally",
    either as real numbers (i.e. signed/unsigned floats or ints), or as
    versions.
  doc_url: http://pythonhosted.org/natsort/
  dev_url: https://github.com/SethMMorton/natsort
