package:
  name: more-itertools
  version: 3.0.0

source:
  fn: more-itertools-3.0.0.tar.gz
  url: https://pypi.python.org/packages/a5/06/f75faf76ec1f7c663a7588bb6d952a02e29db533f86cd280b6b1046a90eb/more-itertools-3.0.0.tar.gz
  md5: a31181a86fe72e8cd9bac9c33afd446a

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - more_itertools

about:
  home: https://github.com/erikrose/more-itertools
  license: MIT
  license_file: LICENSE
  summary: more routines for operating on iterables, beyond itertools
  description: |
    more-itertools, additional building blocks, recipes, and routines for working with Python iterables.
  doc_url: http://more-itertools.readthedocs.io/en/latest/
  doc_source_url: https://github.com/erikrose/more-itertools/blob/master/docs/index.rst
