package:
  name: pyodbc
  version: 4.0.16

source:
  fn: pyodbc-4.0.16.tar.gz
  url: https://pypi.python.org/packages/1a/a1/5d98f9ce7e13d94d379d0f1f7137c7d537330027b912188311b12ef44018/pyodbc-4.0.16.tar.gz
  md5: 4a97e3fe0110495f1a29114690747d91
  patches:
    - setup.patch        [unix]

build:
  number: 0
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - unixodbc 2.3.4     [unix]
  run:
    - python
    - unixodbc 2.3.4     [unix]

test:
  imports:
    - pyodbc

about:
  home: http://mkleehammer.github.io/pyodbc/
  license: MIT
  license_file: LICENSE.txt
  summary: DB API Module for ODBC
  description: |
    pyodbc is a Python 2.x and 3.x module that allows you to use ODBC to
    connect to almost any database from Windows, Linux, OS/X, and more.
  doc_url: http://mkleehammer.github.io/pyodbc/
  dev_url: https://github.com/mkleehammer/pyodbc
