package:
  name: btrees
  version: 4.3.1

source:
  fn: BTrees-4.3.1.tar.gz
  url: https://pypi.python.org/packages/24/76/cd6f225f2180c22af5cdb6656f51aec5fca45e45bdc4fa75c0a32f161a61/BTrees-4.3.1.tar.gz
  md5: cf6a994b54df253de2a74e05904534c9

requirements:
  build:
    - python
    - setuptools
    - persistent
  run:
    - python
    - persistent

test:
  imports:
    - BTrees

about:
  home: http://packages.python.org/BTrees
  license: ZPL 2.1
  license_family: Other
  license_file: LICENSE.txt
  summary: scalable persistent object containers
  description: |
    BTrees contains a set of persistent object containers built around a
    modified BTree data structure. The trees are optimized for use inside
    ZODB's "optimistic currency" paradigm, and include explicit resolution of
    conflicts detected by that mechanism.
  doc_url: http://pythonhosted.org/BTrees
  dev_url: https://github.com/zopefoundation/BTrees
