package:
  name: botocore
  version: 1.4.58

source:
  fn: botocore-1.4.58.tar.gz
  url: https://pypi.python.org/packages/48/46/9f178ccd2b6c95cf90be659811c787b92f0168a041c7539711479c67ecb2/botocore-1.4.58.tar.gz
  md5: 5795965788d87ae0865791502b8fa200

requirements:
  build:
    - python
    - setuptools
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10
    - jmespath >=0.7.1,<1.0.0
  run:
    - python
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10
    - jmespath >=0.7.1,<1.0.0

test:
  imports:
    - botocore

about:
  home: http://aws.amazon.com/sdk-for-python/
  license: Apache
  license_file: LICENSE.txt
  summary: low-level, core functionality of boto3
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  doc_url: https://boto3.readthedocs.org
  dev_url: https://github.com/boto/boto3
