package:
  name: boto3
  version: 1.4.0

source:
  fn: boto3-1.4.0.tar.gz
  url: https://pypi.python.org/packages/37/1a/e271b2937c05c1da265415103725e0610fb96871a2d7ddf68b999ac5db8f/boto3-1.4.0.tar.gz
  md5: 4b5454e8d29dede99092616023828a21

requirements:
  build:
    - python
    - setuptools
    - botocore >=1.4.1,<1.5.0
    - jmespath >=0.7.1,<1.0.0
    - s3transfer >=0.1.0,<0.2.0
  run:
    - python
    - botocore >=1.4.1,<1.5.0
    - jmespath >=0.7.1,<1.0.0
    - s3transfer >=0.1.0,<0.2.0

test:
  imports:
    - boto3

about:
  home: http://aws.amazon.com/sdk-for-python/
  license: MIT
  license_file: LICENSE
  summary: Amazon Web Services SDK for Python
  description: |
    Boto3 makes it easy to integrate you Python application, library or script
    with AWS services. It allows Python developers to write softare that makes
    use of services like Amazon S3 and Amazon EC2.
  doc_url: https://boto3.readthedocs.org
  dev_url: https://github.com/boto/boto3
