package:
  name: affine
  version: 2.0.0

source:
  git_url: https://github.com/sgillies/affine.git
  git_tag: 2.0.0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - affine

about:
  home: https://github.com/sgillies/affine
  license: BSD
  license_file: LICENSE.txt
  summary: Matrices describing affine transformation of the plane.
  description: |
    The Affine package is used to produce the affine transformation
    matrix.
  doc_url: https://anaconda.org/anaconda/affine
  dev_url: https://github.com/ContinuumIO/anaconda/tree/master/packages/affine
