package:
  name: nltk
  version: 3.2.3

source:
  fn: nltk-3.2.3.tar.gz
  url: https://pypi.python.org/packages/af/db/04baa1b45cd141f1a867a95f7766a0bbda00590cdea9b695010f92682b26/nltk-3.2.3.tar.gz
  md5: ab49de67fc7abc801208194f35ddb977

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests
    - six

test:
  imports:
    - nltk

about:
  home: http://nltk.org/
  license: Apache Software License
  license_family: Apache
  license_file: LICENSE.txt
  summary: Build Python programs to work with human language data
  description: |
    NLTK is a leading platform for building Python programs to work with human
    language data. It provides easy-to-use interfaces to over 50 corpora and
    lexical resources such as WordNet, along with a suite of text processing
    libraries for classification, tokenization, stemming, tagging, parsing,
    and semantic reasoning, wrappers for industrial-strength NLP libraries,
    and an active discussion forum.
  doc_url: http://www.nltk.org/
  dev_url: https://github.com/nltk/nltk
