package:
  name: pillow
  version: 4.1.1

source:
  fn: Pillow-4.1.1.tar.gz
  url: https://pypi.python.org/packages/93/73/66854f63b1941aad9af18a1de59f9cf95ad1a87c801540222e332f6688d7/Pillow-4.1.1.tar.gz
  md5: f2565954955c8d10f3b4f1f72f852bf7
  patches:
    - freetype_win_link.patch   [win]

build:
  detect_binary_files_with_prefix: False
  number: 0

requirements:
  build:
    - python
    - zlib 1.2.*
    - libpng 1.6.27
    - libtiff 4.0.6
    - jpeg 9b
    - freetype 2.5.*
    - setuptools
    - bzip2 1.0.6        [win]
  run:
    - python
    - jpeg 9*
    - zlib 1.2.*
    - freetype 2.5.*
    - libtiff 4.0.*
    - olefile
    - bzip2 1.0.6        [win]

test:
  imports:
    - PIL
    - PIL.Image
    - PIL._imaging
    - PIL._imagingft
    - PIL._imagingmath
    - PIL._imagingmorph
    - PIL._imagingtk     [linux and not (arm or ppc64le)]

about:
  home: http://python-pillow.github.io/
  license: PIL license
  license_family: Other
  license_file: LICENSE
  summary: The friendly Python Imaging Library(PIL) fork
  description: |
    Pillow is he friendly PIL fork. PIL is the Python Imaging Library. If you
    have ever worried or wondered about the future of PIL, please stop. We're
    here to save the day.
  doc_url: http://pillow.readthedocs.org/en/3.2.x/
  dev_url: https://github.com/python-pillow/Pillow
