package:
  name: pandas-datareader
  version: 0.2.1

source:
  fn: pandas-datareader-0.2.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pandas-datareader/pandas-datareader-0.2.1.tar.gz
  md5: 24554e0abc30c1f9dad6c4acb4bd84bb

requirements:
  build:
    - python
    - setuptools
    - pandas
    - requests
    - requests-file
  run:
    - python
    - pandas
    - requests
    - requests-file

test:
  imports:
    - pandas_datareader
    - pandas_datareader.google
    - pandas_datareader.io
    - pandas_datareader.io.tests
    - pandas_datareader.yahoo

about:
  home: https://github.com/pydata/pandas-datareader
  license: BSD
  license_file: LICENSE.md
  summary: data readers extracted from the pandas codebase
  description: |
    Up to date remote data access for pandas, works for multiple versions
    of pandas.
  doc_url: http://pandas-datareader.readthedocs.org/en/latest/
  doc_source_url: https://github.com/pydata/pandas-datareader/blob/master/docs/source/index.rst
  dev_url: https://github.com/pydata/pandas-datareader
