package:
  name: pandas-datareader
  version: 0.4.0

source:
  fn: pandas-datareader-0.4.0.tar.gz
  url: https://pypi.python.org/packages/e5/ed/2baf33e80db8791614c9a680cea0ab839e00448070becb7198f8a3c80629/pandas-datareader-0.4.0.tar.gz
  md5: 3ee5c5e16c040f00b658d2e1db45ed0e

requirements:
  build:
    - python
    - setuptools
    - pandas
    - requests
    - requests-file
  run:
    - python
    - pandas >=0.17.0
    - requests >=2.3.0
    - requests-file
    - requests-ftp

test:
  imports:
    - pandas_datareader
    - pandas_datareader.google
    - pandas_datareader.io
    - pandas_datareader.tests
    - pandas_datareader.yahoo

about:
  home: https://github.com/pydata/pandas-datareader
  license: BSD
  license_file: LICENSE.md
  summary: data readers extracted from the pandas codebase
  description: |
    Up to date remote data access for pandas, works for multiple versions
    of pandas.
  doc_url: http://pandas-datareader.readthedocs.org/en/latest/
  doc_source_url: https://github.com/pydata/pandas-datareader/blob/master/docs/source/index.rst
  dev_url: https://github.com/pydata/pandas-datareader
