package:
  name: qtpy
  version: 1.2.1

source:
  fn: QtPy-1.2.1.tar.gz
  url: https://pypi.python.org/packages/0a/a8/31632a1c7cab273ac801da8b610d8659195853c099e1a26bfc08e78ddbe6/QtPy-1.2.1.tar.gz
  md5: e2f783fb7f8e502815237bd8d30c6d11

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pyqt
  imports:
    - qtpy

about:
  home: https://github.com/spyder-ide/qtpy
  license: MIT
  summary: Abtraction layer for PyQt5/PyQt4/PySide
  description: |
    QtPy is a small abstraction layer that lets you write applications using a
    single api call to either PyQt or PySide.
  doc_url: https://pypi.python.org/pypi/QtPy
  doc_source_url: https://github.com/spyder-ide/qtpy
