package:
  name: qtconsole
  version: 4.3.0

source:
  fn: qtconsole-4.3.0.tar.gz
  url: https://pypi.python.org/packages/cc/97/41fb735c918bfb3d9bac3fa8347addc2ffc82fd06084940a1821cf333ac8/qtconsole-4.3.0.tar.gz
  md5: e8fb599d209e3e55aa593c5b25d898ac

build:
  entry_points:
    - jupyter-qtconsole = qtconsole.qtconsoleapp:main

requirements:
  build:
    - python
  run:
    - python
    - pyqt 5.*
    - traitlets
    - ipython_genutils
    - jupyter_core
    - jupyter_client >=4.1
    - pygments
    - ipykernel >=4.1

app:
  entry: jupyter-qtconsole
  icon: jupyter.png
  summary: Jupyter Qt console
  type: desk

test:
  imports:
    - qtconsole

about:
  home: http://jupyter.org
  license: Modified BSD License
  license_family: BSD
  license_file: COPYING.md
  summary: Jupyter Qt Console
  description: |
    The Qt console is a very lightweight application that largely feels like a terminal, but provides
    a number of enhancements only possible in a GUI, such as inline figures,
    proper multiline editing with syntax highlighting, graphical calltips and
    more.
  doc_url: https://qtconsole.readthedocs.org/en/stable/
  doc_source_url: https://github.com/jupyter/qtconsole/blob/master/docs/source/index.rst
  dev_url: https://github.com/jupyter/qtconsole
