package:
  name: azure
  version: 1.0.2

source:
  git_url: https://github.com/Azure/azure-sdk-for-python.git
  git_tag: v1.0.2

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - requests

test:
  imports:
    - azure
    - azure.common
    - azure.mgmt
    - azure.servicebus
    - azure.servicemanagement

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache License 2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Microsoft Azure SDK for Python
  description: |
   Azure provides Python packages that make it easy to access Microsoft
   Azure components.
  doc_url: https://azure.microsoft.com/en-us/documentation
  dev_url: https://github.com/Azure
