package:
  name: ipykernel
  version: 4.6.1

source:
  fn: ipykernel-4.6.1.tar.gz
  url: https://pypi.python.org/packages/0c/41/67e16b243b78b49f4b1650d045b63be187c27d20a76f0f7b8e61e0fcb966/ipykernel-4.6.1.tar.gz
  md5: 1b320ff87a1a0b049e83df2de91b7f7c

requirements:
  build:
    - python
    - ipython
    - jupyter_client
  run:
    - python
    - ipython >=4.0.0
    - traitlets >=4.1.0
    - jupyter_client
    - tornado >=4.0

test:
  imports:
    - ipykernel

about:
  home: http://ipython.org
  license: BSD
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter
  description: |
    A powerful interactive shell.
    A kernel for Jupyter.
    Support for interactive data visualization and use of GUI toolkits.
    Flexible, embeddable interpreters to load into your own projects.
    Easy to use, high performance tools for parallel computing.
  doc_url: http://ipython.readthedocs.org/
  dev_url: https://github.com/ipython/ipython
