package:
  name: qgrid
  version: 0.3.2

source:
  fn: qgrid-0.3.2.tar.gz
  url: https://pypi.python.org/packages/80/ae/89dfb52b93a62ace8821172ffde518d480c3700648ee4a428ff45537de0f/qgrid-0.3.2.tar.gz
  md5: d67be966d98b2aa9ef32fe37fd29c7ab

requirements:
  build:
    - python
    - setuptools
    - notebook >=4.1.0
    - pandas >=0.17.1
    - ipywidgets >=4.1.1
  run:
    - python
    - notebook >=4.1.0
    - pandas >=0.17.1
    - ipywidgets >=4.1.1

test:
  imports:
    - qgrid
    - qgrid.qgridjs

about:
  home: https://github.com/quantopian/qgrid
  license: Apache
  summary: Pandas DataFrame viewer for IPython Notebook
  description: |
    Qgrid is an IPython widget which uses SlickGrid to render pandas
    DataFrames within a Jupyter notebook. This allows you to explore your
    DataFrames with intuitive scrolling, sorting, and filtering controls, as
    well as edit your DataFrames by double clicking a cell.
  doc_url: http://qgrid.readthedocs.org/en/latest/
  doc_source_url: https://github.com/quantopian/qgrid/blob/master/docs/index.rst
  dev_url: https://github.com/quantopian/qgrid
