package:
  name: idna
  version: 2.5

source:
  fn: idna-2.5.tar.gz
  url: https://pypi.python.org/packages/d8/82/28a51052215014efc07feac7330ed758702fc0581347098a81699b5281cb/idna-2.5.tar.gz
  md5: fc1d992bef73e8824db411bb5d21f012

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - idna
    - idna.codec

about:
  home: https://github.com/kjd/idna
  license: BSD
  license_file: LICENSE.rst
  summary: Internationalized Domain Names in Applications
  description: |
    This acts as a suitable replacement
    for the encodings.idna module that comes with the Python standard library,
    but only supports the old, deprecated IDNA specification (RFC 3490).
  doc_url: https://pypi.python.org/pypi/idna/2.5
  doc_source_url: https://github.com/kjd/idna/blob/master/README.rst
