package:
  name: idna
  version: 2.5

source:
  fn: idna-2.5.tar.gz
  url: https://pypi.python.org/packages/d8/82/28a51052215014efc07feac7330ed758702fc0581347098a81699b5281cb/idna-2.5.tar.gz
  md5: fc1d992bef73e8824db411bb5d21f012

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - idna
    - idna.codec

about:
  home: https://github.com/kjd/idna
  license: BSD
  license_file: LICENSE.rst
  summary: Internationalized Domain Names in Applications
  description: |
    A library to support the Internationalised Domain Names in Applications
    (IDNA) protocol as specified in RFC 5891. This version of the protocol is
    often referred to as "IDNA2008".
