package:
  name: pathlib2
  version: 2.2.1

source:
  fn: pathlib2-2.2.1.tar.gz
  url: https://pypi.python.org/packages/ab/d8/ac7489d50146f29d0a14f65545698f4545d8a6b739b24b05859942048b56/pathlib2-2.2.1.tar.gz
  md5: 6c75bfde898b6c88627621a48ee8de14

requirements:
  build:
    - python
    - setuptools
    - six
    - scandir          [py < 35]
  run:
    - python
    - six
    - scandir          [py < 35]

test:
  imports:
    - pathlib2

about:
  home: https://pypi.python.org/pypi/pathlib2/
  license: MIT
  license_file: LICENSE.rst
  summary: object-oriented filesystem paths
  description: |
    The goal of pathlib2 is to provide a backport of standard pathlib module which
    tracks the standard library module, so all the newest features of the standard
    pathlib can be used also on older Python versions.
  doc_url: https://pypi.python.org/pypi/pathlib2/
  doc_source_url: https://github.com/mcmtroffaes/pathlib2/blob/develop/README.rst
