package:
  name: snappy
  version: 1.1.4

source:
  git_url: https://github.com/google/snappy.git
  git_tag: 1.1.4

build:
  features:
    - vc9             [win and py27]
    - vc14            [win and (py35 or py36)]

requirements:
  build:
    - git            [unix]
    - libtool        [unix]
    - automake       [unix]
    - pkg-config     [unix]
    - m2-git         [win]
    - m2-filesystem  [win]
  run:
    - vc 9     [win and py27]
    - vc 14    [win and (py35 or py36)]

about:
  home: https://github.com/google/snappy
  license: Other
  license_family: Other
