package:
  name: markdown2
  version: 2.3.4

source:
  fn: markdown2-2.3.4.zip
  url: https://pypi.python.org/packages/f2/3e/8836dd370419e928ac9856ab582d92e46292e09bfa9917bec81ca7444e3a/markdown2-2.3.4.zip
  md5: fa89c7d410df789866dcf471d321ec5f

build:
  entry_points:
    - markdown2 = markdown2:main

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - markdown2 --help
  imports:
    - markdown2

about:
  home: http://packages.python.org/Markdown/
  license: MIT
  license_file: LICENSE.txt
  summary: Python implementation of Markdown
  description: |
    A Python implementation of John Gruber's Markdown. It is almost completely
    compliant with the reference implementation, though there are a few known
    issues.
  doc_url: https://pythonhosted.org/Markdown/
  dev_url: https://github.com/waylan/Python-Markdown
