package:
  name: anaconda-verify
  version: 1.2.1

source:
  git_url: https://github.com/ContinuumIO/anaconda-verify.git
  git_tag: 1.2.1

build:
  entry_points:
    - anaconda-verify = anaconda_verify.main:main

requirements:
  build:
    - python
  run:
    - python
    - pyyaml

test:
  commands:
    - anaconda-verify
  imports:
    - anaconda_verify

about:
  home: https://github.com/ContinuumIO/anaconda-verify
  license: BSD
  license_file: LICENSE.txt
  summary: tool for (passively) verifying conda recipes and conda packages
