package:
  name: werkzeug
  version: 0.12.2

source:
  fn: Werkzeug-0.12.2.tar.gz
  url: https://pypi.python.org/packages/56/41/c095a77eb2dd69bf278dd664a97d3416af04e9ba1a00b8c138f772741d31/Werkzeug-0.12.2.tar.gz
  md5: e385b2c5a7193cff24c689b31e1124dc

requirements:
  build:
    - python
    # the reason we use setuptools here is because otherwise the package data
    # files don't get installed
    - setuptools
  run:
    - python

test:
  imports:
    - werkzeug
    - werkzeug.debug
    - werkzeug.contrib

about:
  home: http://werkzeug.pocoo.org/
  license: BSD
  license_file: LICENSE
  summary: A WSGI utility library for Python
  description: |
    Werkzeug started as simple collection of various utilities for WSGI
    applications and has become one of the most advanced WSGI utility modules.
    It includes a powerful debugger, full-featured request and response
    objects, HTTP utilities to handle entity tags, cache control headers,
    HTTP dates, cookie handling, file uploads, a powerful URL routing system
    and a bunch of community-contributed addon modules.
  doc_url: http://werkzeug.pocoo.org/docs/0.11/
  dev_url: https://github.com/pallets/werkzeug
