package:
  name: dask
  version: 0.14.3

source:
  fn: dask-0.14.3.tar.gz
  url: https://pypi.python.org/packages/a3/76/9dbbea3d9cf13bce2ed535142545bf2db259ebd809fe7017bb863be2cf5a/dask-0.14.3.tar.gz
  md5: 059ff19c01b93c2781b6fff09182dfce

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - bokeh
    - cloudpickle >=0.2.1
    - numpy
    - pandas >=0.19.0
    - partd >=0.3.7
    - toolz >=0.7.3

test:
  imports:
    - dask
    - dask.core
    - dask.array
    - dask.bag

about:
  home: http://dask.pydata.org/en/latest/
  license: BSD
  license_file: LICENSE.txt
  summary: Task scheduling and blocked algorithms for parallel processing
  description: |
    Dask is a flexible parallel computing library for analytic computing.
  doc_url: http://dask.pydata.org
  doc_source_url: https://github.com/dask/dask/blob/master/docs/source/index.rst
  dev_url: https://github.com/dask/dask
