package:
  name: dask
  version: 0.15.1

source:
  fn: dask-0.15.1.tar.gz
  url: https://pypi.python.org/packages/78/0b/3d4e3cefe36e84e2e35b9ab9f45c570b7a358fa8a319e36bf12add73c64c/dask-0.15.1.tar.gz
  md5: 275d8ad0c5c6460ef022d06aa77f4bb2

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - bokeh
    - cloudpickle >=0.2.1
    - numpy
    - pandas >=0.19.0
    - partd >=0.3.8
    - toolz >=0.7.3

test:
  imports:
    - dask
    - dask.core
    - dask.array
    - dask.bag

about:
  home: http://dask.pydata.org/en/latest/
  license: BSD
  license_file: LICENSE.txt
  summary: Task scheduling and blocked algorithms for parallel processing
  description: |
    Dask is a flexible parallel computing library for analytic computing.
  doc_url: http://dask.pydata.org
  doc_source_url: https://github.com/dask/dask/blob/master/docs/source/index.rst
  dev_url: https://github.com/dask/dask
