# NOTE: this is a meta-package that includes the core glue code as well as stable
# plugins. This is the main conda package we want in the Navigator, so we add the
# app: entry here and not in the glue-core package.

package:
  name: glueviz
  version: 0.10.1

source:
  fn: glueviz-0.10.1.tar.gz
  url: https://pypi.io/packages/source/g/glueviz/glueviz-0.10.1.tar.gz
  md5: abcb117e102ae9cb00c5dd1bd784c5f3

requirements:

  build:
    - python
    - setuptools

  run:
    - glue-core >=0.10.1
    - glue-vispy-viewers >=0.7.2

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

test:
  imports:
    - glue
    - glue.core
    - glue.app.qt
  commands:
    - glue --version
    - glue-deps list

about:
  home: http://glueviz.org/
  license: 3-clause BSD License
  license_family: BSD
  # TMP: license file is missing in 0.10.1
  #license_file: LICENSE
  summary: Multi-dimensional linked data exploration
  description: |
    Glue is a Python library to explore relationships within and among related
    datasets. Its main features include Linked Statistical Graphics, flexible
    linking across data and full scripting capability.
  doc_url: http://www.glueviz.org/
  dev_url: https://github.com/glue-viz/glueviz-meta
