package:
  name: plotly
  version: 2.0.9

source:
  fn: plotly-2.0.9.tar.gz
  url: https://pypi.python.org/packages/36/29/bda764086e27dacc61ef5b038b9b179a1c7791b5304f5c7b83f5b8c007ce/plotly-2.0.9.tar.gz
  md5: 8890f487f0cdd448e390c68f0dc69ba3

requirements:
  build:
    - python
    - setuptools
    - requests
    - six
    - pytz
  run:
    - python
    - setuptools
    - requests
    - decorator >=4.0.6
    - nbformat >=4.2
    - six
    - pytz

test:
  imports:
    - plotly
    - plotly.graph_objs
    - plotly.grid_objs
    - plotly.offline
    - plotly.plotly

about:
  home: https://plot.ly/python/
  license: MIT
  summary: plotting library for collaborative, interactive, publication-quality graphs
  description: |
    Plotly is the collaboration platform for modern data science.
  doc_url: https://plot.ly/api/
  doc_source_url: https://github.com/plotly/documentation/blob/master/README.md
