package:
  name: zope.interface
  version: 4.4.0

source:
  fn: zope.interface-4.4.0.tar.gz
  url: https://pypi.python.org/packages/36/f6/1c2d593acb13562831631c281d75bd0091c50b0c004106d9823da784c3af/zope.interface-4.4.0.tar.gz
  md5: cdc6b9b5e1f53e8ff018d357f44c789e

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools
    - zope
  run:
    - python
    - zope

test:
  imports:
    - zope.interface
    - zope.interface.common.mapping
    - zope.interface._zope_interface_coptimizations

about:
  home: http://docs.zope.org/zope.interface/
  license: ZPL 2.1
  license_family: Other
  license_file: LICENSE.txt
  summary: Interfaces for Python
  description: |
    Provides an implementation of "object interfaces" for Python. Interfaces
    are a mechanism for labeling objects as conforming to a given API or
    contract.
  doc_url: http://docs.zope.org/zope.interface/
  dev_url: https://github.com/zopefoundation/zope.interface
