package:
  name: zope.interface
  version: 4.4.1

source:
  fn: zope.interface-4.4.1.tar.gz
  url: https://pypi.python.org/packages/90/1c/942298a4f5ef7db8c885ae687c59d397127f5a8cff7a473b0d7475a2c6e7/zope.interface-4.4.1.tar.gz
  md5: 346511e04ed6fbe5e479425762818d5c

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools
    - zope
  run:
    - python
    - zope

test:
  imports:
    - zope.interface
    - zope.interface.common.mapping
    - zope.interface._zope_interface_coptimizations

about:
  home: http://docs.zope.org/zope.interface/
  license: ZPL 2.1
  license_family: Other
  license_file: LICENSE.txt
  summary: Interfaces for Python
  description: |
    Provides an implementation of object interfaces for Python.Interfaces are objects
    that specify the external behavior of objects that provide them.
  doc_url: http://docs.zope.org/zope.interface/
  doc_source_url: https://github.com/zopefoundation/zope.interface//blob/master/docs/index.rst
  dev_url: https://github.com/zopefoundation/zope.interface
