package:
  name: widgetsnbextension
  version: 3.0.1

source:
  fn: widgetsnbextension-3.0.1.tar.gz
  url: https://pypi.python.org/packages/46/30/23d7d7460ab19d40bb89e0b0a1905910009cd92494c7a0dc8f24f87d8a3b/widgetsnbextension-3.0.1.tar.gz
  md5: 098464f4cf1e009f59ad3e6d2c8c2331

requirements:
  build:
    - python
    - setuptools
    - notebook >=4.4.1
  run:
    - python
    - notebook >=4.4.1

test:
  imports:
    - widgetsnbextension

about:
  home: http://ipython.org
  license: BSD 3-clause
  license_family: BSD
  summary: IPython HTML widgets for Jupyter
  description: |
    Interactive HTML widgets for Jupyter notebooks.
  doc_url: https://pypi.python.org/pypi/widgetsnbextension
