package:
  name: service_identity
  version: 16.0.0

source:
  fn: service_identity-16.0.0.tar.gz
  url: https://pypi.python.org/packages/source/s/service_identity/service_identity-16.0.0.tar.gz
  md5: d52392597b9c44a740abf322bfdb21e6

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - attrs
    - pyasn1
    - pyasn1-modules
    - pyopenssl >=0.12

test:
  imports:
    - service_identity

about:
  home: https://github.com/pyca/service_identity
  license: MIT
  license_file: LICENSE
  summary: Service identity verification for pyOpenSSL
  description: |
    service_identity aspires to give you all the tools you need for verifying
    whether a certificate is valid for the intended purposes.
  doc_url: https://service-identity.readthedocs.org/en/stable/
  doc_source_url: https://github.com/pyca/service_identity/blob/master/docs/index.rst
  dev_url: https://github.com/pyca/service_identity
