package:
  name: lz4
  version: 0.10.0

source:
  fn: lz4-0.10.0.tar.gz
  url: https://pypi.python.org/packages/1b/69/6c106a77a804f08938487a9bf45a9771209f487c9dadea8ea819c1555e35/lz4-0.10.0.tar.gz
  md5: 46f2b225747703aa8b12e003604bdcef

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools_scm
    - nose
  run:
    - python

test:
  imports:
    - lz4

about:
  home: https://github.com/steeve/python-lz4
  license: BSD
  license_file: LICENSE
  summary: Bindings for the lz4 compression library
  description: |
    Provides a Python interface for the LZ4 compression library.
    LZ4 library provides support for three specifications-
    frame format,block format and stream format.
  doc_url: http://python-lz4.readthedocs.io/en/latest/
  doc_source_url: https://github.com/python-lz4/python-lz4/blob/master/docs/index.rst
  dev_url: https://github.com/steeve/python-lz4
