package:
  name: lz4
  version: 0.9.1

source:
  fn: lz4-0.9.1.tar.gz
  url: https://pypi.python.org/packages/63/30/e05274f250106a7a3c0a84ff261c18b78d4d9ece655af05660959d3e5b14/lz4-0.9.1.tar.gz
  md5: 5455f33963794c8d65f64e9d347c7aa7

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools_scm
    - nose
  run:
    - python

test:
  imports:
    - lz4

about:
  home: https://github.com/steeve/python-lz4
  license: BSD
  license_file: LICENSE
  summary: Bindings for the lz4 compression library
  description: |
    Provides a Python interface for the LZ4 compression library.
    LZ4 library provides support for three specifications-
    frame format,block format and stream format.
  doc_url: http://python-lz4.readthedocs.io/en/latest/
  doc_source_url: https://github.com/python-lz4/python-lz4/blob/master/docs/index.rst
  dev_url: https://github.com/steeve/python-lz4
