package:
  name: lz4
  version: 0.9.4

source:
  fn: lz4-0.9.4.tar.gz
  url: https://pypi.python.org/packages/47/84/f61915f91b52c591e499a783e6d64c27cc62a4d535a722d78752dbe85678/lz4-0.9.4.tar.gz
  md5: 9d44f57a8926fd2494a0d23b1c4509f5

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools_scm
    - nose
  run:
    - python

test:
  imports:
    - lz4

about:
  home: https://github.com/steeve/python-lz4
  license: BSD
  license_file: LICENSE
  summary: Bindings for the lz4 compression library
  description: |
    Provides a Python interface for the LZ4 compression library.
    LZ4 library provides support for three specifications-
    frame format,block format and stream format.
  doc_url: http://python-lz4.readthedocs.io/en/latest/
  doc_source_url: https://github.com/python-lz4/python-lz4/blob/master/docs/index.rst
  dev_url: https://github.com/steeve/python-lz4
