package:
  name: biopython
  version: 1.68

source:
  fn: biopython-1.68.tar.gz
  url: https://pypi.python.org/packages/72/6c/e1e13b9df73f9c2539b67d12bc22be6b19779230cadbed04c24f3f3e5ef4/biopython-1.68.tar.gz
  md5: 078e915185485a5327937029b7577ddc

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - numpy x.x
  run:
    - python
    - numpy x.x

test:
  imports:
    - Bio
    - BioSQL

about:
  home: http://biopython.org/
  license: Biopython or BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Freely available tools for biological computation
  description: |
    Biopython Project is an international association of developers of freely
    available Python tools for computational molecular biology.
  doc_url: http://biopython.org/wiki/Documentation
  doc_source_url: https://github.com/biopython/biopython.github.io/edit/master/index.md
  dev_url: https://github.com/biopython/biopython
