package:
  name: smart_open
  version: 1.5.2

source:
  fn: smart_open-1.5.2.tar.gz
  url: https://pypi.python.org/packages/b3/f4/17b0a41471ee8e9009c260f214b66cf166dc2d7f18ddb82450e09724f663/smart_open-1.5.2.tar.gz
  md5: 1ae4eae45c13eed4336a60ba24192578

requirements:
  build:
    - python
    - setuptools
    - boto >=2.32
    - bz2file
    - requests
  run:
    - python
    - boto >=2.32
    - bz2file
    - requests

test:
  imports:
    - smart_open

about:
  home: https://github.com/piskvorky/smart_open
  license: MIT
  license_file: LICENSE
  summary: library for streaming large files
  description: |
    smart_open is a Python library for efficient streaming of
    very large files from/to S3, HDFS, WebHDFS or local (compressed) files.
  doc_url: https://pypi.python.org/pypi/smart_open
  doc_source_url: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst
  dev_url: https://github.com/piskvorky/smart_open
