package:
  name: thinc
  version: 6.7.3

source:
  fn: thinc-6.7.3.tar.gz
  url: https://pypi.python.org/packages/17/d6/2e54a1abe6688fcda3faa81222a5a1bcdffa286124769f11b3e3d4be9443/thinc-6.7.3.tar.gz
  md5: 549ecb152330d96a679e03a744eda5a3

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - wrapt
    - murmurhash >=0.28,<0.29
    - cymem >=1.30,<1.32
    - preshed >=1.0.0,<2.0.0
    - chainer ==1.24.0
    - tqdm >=4.10.0,<5.0.0
    - cytoolz >=0.8,<0.9
    - plac >=0.9.6,<1.0.0
    - six >=1.10.0,<2.0.0
    - dill
    - termcolor
    - pathlib >=1.0.0,<2.0.0
    - msgpack-python
    - msgpack-numpy
  run:
    - python
    - numpy
    - wrapt
    - murmurhash >=0.28,<0.29
    - cymem >=1.30,<1.32
    - preshed >=1.0.0,<2.0.0
    - chainer ==1.24.0
    - tqdm >=4.10.0,<5.0.0
    - cytoolz >=0.8,<0.9
    - plac >=0.9.6,<1.0.0
    - six >=1.10.0,<2.0.0
    - dill
    - termcolor
    - pathlib >=1.0.0,<2.0.0
    - msgpack-python
    - msgpack-numpy

test:
  imports:
    - thinc

about:
  home: https://github.com/explosion/thinc
  license: MIT
  license_file: LICENSE
  summary: Learn sparse linear models
  description: |
    thinc is a Cython library for learning models with millions of parameters
    and dozens of classes.
