package:
  name: bokeh
  version: 0.12.6

source:
  fn: bokeh-0.12.6.tar.gz
  url: https://pypi.python.org/packages/45/6c/6d1ad9da2e713f69d3df6e4e5eb3e8f971db03e66f3154c9e5ab142a6bd8/bokeh-0.12.6.tar.gz
  md5: b7aa11af421e0afa4834128a2c2a5ca7

build:
  entry_points:
    - bokeh = bokeh.__main__:main

requirements:
  build:
    - python
    - setuptools
    - six
    - requests
    - pyyaml
    - python-dateutil >=2.1
    - jinja2 >=2.7
    - numpy
    - tornado >=4.3
    - bkcharts >=0.2
    - futures >=3.0.3        [py27]
  run:
    - python
    - six >=1.5.2
    - requests >=1.2.3
    - pyyaml >=3.10
    - python-dateutil >=2.1
    - jinja2 >=2.7
    - numpy
    - tornado >=4.3
    - bkcharts >=0.2
    - futures >=3.0.3        [py27]

test:
  commands:
    - bokeh -h
  imports:
    - bokeh
    - bokeh.application
    - bokeh.models
    - bokeh.models.widgets
    - bokeh.sampledata
    - bokeh.server
    - bokeh.sphinxext
    - bokeh.util

about:
  home: http://bokeh.pydata.org/
  license: BSD
  license_file: LICENSE.txt
  summary: Python interactive visualization library for modern web browsers
  description: |
    Bokeh is a Python interactive visualization library that targets
    modern web browsers for presentation. Its goal is to provide elegant,
    concise  construction of novel graphics in the style of D3.js, and to
    extend this capability with high-performance interactivity over very
    large or streaming datasets. Bokeh can help anyone who would like to
    quickly and easily create interactive plots, dashboards, and data
    applications.
  doc_url: http://bokeh.pydata.org/en/latest/docs/user_guide.html
  dev_url: http://github.com/bokeh/bokeh
