package:
  name: botocore
  version: 1.5.47

source:
  fn: botocore-1.5.47.tar.gz
  url: https://pypi.python.org/packages/a0/4d/3b94847f63b79c2cadf59c6ae3dcde363eb0bfd13f1bcf58523e349c5ed0/botocore-1.5.47.tar.gz
  md5: f9c635742b1f694d3c94f34d03a7f929

requirements:
  build:
    - python
    - setuptools
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10
    - jmespath >=0.7.1,<1.0.0
  run:
    - python
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10
    - jmespath >=0.7.1,<1.0.0

test:
  imports:
    - botocore

about:
  home: http://aws.amazon.com/sdk-for-python/
  license: Apache License 2.0
  license_url: http://aws.amazon.com/apache2.0/
  license_family: Apache
  license_file: LICENSE.txt
  summary: low-level, core functionality of boto3
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  doc_url: https://boto3.readthedocs.org
  dev_url: https://github.com/boto/boto3
