package:
  name: botocore
  version: 1.5.61

source:
  fn: botocore-1.5.61.tar.gz
  url: https://pypi.python.org/packages/2f/e9/6b624cf4dc9f7d594948b5d2c8b610a9e947bfc9e1fdd6521b30297465ff/botocore-1.5.61.tar.gz
  md5: 7cfe82dacedc7b8cd87a1c15dec9eb62

requirements:
  build:
    - python
    - setuptools
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10
  run:
    - python
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10

test:
  imports:
    - botocore

about:
  home: http://aws.amazon.com/sdk-for-python/
  license: Apache License 2.0
  license_url: http://aws.amazon.com/apache2.0/
  license_family: Apache
  license_file: LICENSE.txt
  summary: low-level, core functionality of boto3
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  doc_url: https://boto3.readthedocs.org
  dev_url: https://github.com/boto/boto3
