package:
  name: botocore
  version: 1.5.58

source:
  fn: botocore-1.5.58.tar.gz
  url: https://pypi.python.org/packages/dc/29/ff036ef46da6226725f660aa85ce317fde58575f11bb386b7c525e282e6a/botocore-1.5.58.tar.gz
  md5: 3a16e62613df4db981c6882bcc995f9c

requirements:
  build:
    - python
    - setuptools
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10
  run:
    - python
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10

test:
  imports:
    - botocore

about:
  home: http://aws.amazon.com/sdk-for-python/
  license: Apache License 2.0
  license_url: http://aws.amazon.com/apache2.0/
  license_family: Apache
  license_file: LICENSE.txt
  summary: low-level, core functionality of boto3
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  doc_url: https://boto3.readthedocs.org
  dev_url: https://github.com/boto/boto3
