package:
  name: botocore
  version: 1.5.57

source:
  fn: botocore-1.5.57.tar.gz
  url: https://pypi.python.org/packages/50/1b/019a103dd205347cb6d801884a3ac1f34c19a04e3ee2e1abed403e8ae0b1/botocore-1.5.57.tar.gz
  md5: 8a0bb20816ee82dfe4abd34a89fa3202

requirements:
  build:
    - python
    - setuptools
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10
  run:
    - python
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10

test:
  imports:
    - botocore

about:
  home: http://aws.amazon.com/sdk-for-python/
  license: Apache License 2.0
  license_url: http://aws.amazon.com/apache2.0/
  license_family: Apache
  license_file: LICENSE.txt
  summary: low-level, core functionality of boto3
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  doc_url: https://boto3.readthedocs.org
  dev_url: https://github.com/boto/boto3
