package:
  name: botocore
  version: 1.5.67

source:
  fn: botocore-1.5.67.tar.gz
  url: https://pypi.python.org/packages/a5/4f/f8c79efcd81774b35ae42cbeeade6b26a79feba4a2941413834fa99a5270/botocore-1.5.67.tar.gz
  md5: 6ff26ed5c350e69e897af2802457dc5e

requirements:
  build:
    - python
    - setuptools
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10
  run:
    - python
    - jmespath >=0.7.1,<1.0.0
    - python-dateutil >=2.1,<3.0.0
    - docutils >=0.10

test:
  imports:
    - botocore

about:
  home: http://aws.amazon.com/sdk-for-python/
  license: Apache License 2.0
  license_url: http://aws.amazon.com/apache2.0/
  license_family: Apache
  license_file: LICENSE.txt
  summary: low-level, core functionality of boto3
  description: |
    Provides the core functionality of Boto3, the AWS SDK for Python
  doc_url: https://boto3.readthedocs.org
  dev_url: https://github.com/boto/boto3
