package:
  name: markdown
  version: 2.6.8

source:
  fn: Markdown-2.6.8.tar.gz
  url: https://pypi.python.org/packages/1d/25/3f6d2cb31ec42ca5bd3bfbea99b63892b735d76e26f20dd2dcc34ffe4f0d/Markdown-2.6.8.tar.gz
  md5: d9ef057a5bd185f6f536400a31fc5d45

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - markdown_py -h                 [unix]
  imports:
    - markdown
    - markdown.extensions

about:
  home: http://packages.python.org/Markdown/
  license: BSD
  license_file: LICENSE.md
  summary: Python implementation of Markdown
  description: |
    A Python implementation of John Gruber's Markdown. It is almost completely
    compliant with the reference implementation, though there are a few known
    issues.
  doc_url: https://pythonhosted.org/Markdown/
  doc_source_url: https://github.com/waylan/Python-Markdown/blob/master/docs/index.txt
  dev_url: https://github.com/waylan/Python-Markdown
