package:
  name: astropy
  version: 2.0

source:
  fn: astropy-2.0.tar.gz
  url: https://pypi.python.org/packages/fc/f9/1d9004730fac3df5ba6c8909817fb3842f9e6f5e0a333226683fe71b76f7/astropy-2.0.tar.gz
  md5: 5b8d4191ea210423826d4a254e984e5d

build:
  detect_binary_files_with_prefix: False
  entry_points:
    - fits2bitmap = astropy.visualization.scripts.fits2bitmap:main
    - fitscheck = astropy.io.fits.scripts.fitscheck:main
    - fitsdiff = astropy.io.fits.scripts.fitsdiff:main
    - fitsheader = astropy.io.fits.scripts.fitsheader:main
    - fitsinfo = astropy.io.fits.scripts.fitsinfo:main
    - samp_hub = astropy.samp.hub_script:hub_script
    - volint = astropy.io.votable.volint:main
    - wcslint = astropy.wcs.wcslint:main

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
  run:
    - python
    - numpy x.x
    - argparse          [py26]
    - pytest >=2.8

test:
  commands:
    - fits2bitmap --help
    - fitscheck --help
    - fitsdiff --help
    - fitsheader --help
    - fitsinfo --help
    - samp_hub --help
    - volint --help
    - wcslint --help
  imports:
    - astropy

about:
  home: http://www.astropy.org/
  license: BSD
  summary: Community-developed Python Library for Astronomy
  description: |
    Astropy is a community-driven package intended to contain much of the core functionality and
    some common tools needed for performing astronomy and astrophysics with Python.
  doc_url: http://docs.astropy.org/en/stable/
  doc_source_url: https://github.com/astropy/astropy/blob/master/docs/index.rst
  dev_url: https://github.com/astropy/astropy
