package:
  name: munch
  version: 2.1.1

source:
  fn: munch-2.1.1.tar.gz
  url: https://pypi.python.org/packages/84/dc/d897cb427f15029e04745a3de611d8ed3d97e9a0ef894547a0ba261f2807/munch-2.1.1.tar.gz
  md5: c25c3d4364f3ece0d20cb4df102a8c36

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - munch

about:
  home: http://github.com/Infinidat/munch
  license: MIT
  summary: dot-accessible dictionary (a la JavaScript objects).
