package:
  name: jupyter_client
  version: 5.0.1

source:
  fn: jupyter_client-5.0.1.tar.gz
  url: https://pypi.python.org/packages/01/6d/1566172f3497c79741774971df80db44e10d3c692801e59f9cd3ea64b19a/jupyter_client-5.0.1.tar.gz
  md5: 73852317f98b85d4ffc6565040c04dd6

requirements:
  build:
    - python
  run:
    - python
    - traitlets
    - jupyter_core
    - pyzmq >=13.0
    - python-dateutil >=2.1

test:
  commands:
    - jupyter-kernelspec -h
  imports:
    - jupyter_client

about:
  home: http://jupyter.org
  license: BSD
  license_file: COPYING.md
  summary: Jupyter protocol implementation and client libraries
  description: |
    jupyter client contains the reference implementation of the Jupyter
    protocol.It also provides Python API for starting, managing and
    communicating with Jupyter kernels.
  doc_url: http://jupyter-client.readthedocs.org/
  doc_source_url: https://github.com/jupyter/jupyter_client/blob/master/docs/index.rst
  dev_url: https://github.com/jupyter/jupyter_client
