package:
  name: pymongo
  version: 3.3.0

source:
  fn: pymongo-3.3.0.tar.gz
  url: https://pypi.python.org/packages/31/63/5a7826bdee88db6d49ef1737a17de63cf6f50f8cb04f2a0339f048cb33b5/pymongo-3.3.0.tar.gz
  md5: 42cd12a5014fb7d3e1987ca04f5c651f

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - bson
    - gridfs
    - pymongo
    - bson._cbson
    - pymongo._cmessage

about:
  home: http://github.com/mongodb/mongo-python-driver
  license: Apache
  license_file: LICENSE
  summary: Python driver for MongoDB
  description: |
    PyMongo is a Python distribution containing tools for working with MongoDB
    and is the recommended way to work with MongoDB from Python.
  doc_url: http://api.mongodb.org/python/
  doc_source_url: https://github.com/mongodb/mongo-python-driver/blob/master/doc/index.rst
  dev_url: https://github.com/mongodb/mongo-python-driver
