package:
  name: matplotlib
  version: 2.0.1

source:
  url: https://pypi.python.org/packages/8f/d5/1488c5d7690fd95f91934cdce74292473e760a8dd0d8bf263fd9305728f1/matplotlib-2.0.1.tar.gz
  md5: 055407dc168a12c736bb65943c0d0368
  patches:
    - cfg.patch
    - cfg_notests.patch
    - cfg_qt4agg.patch           [not (osx or ppc64le)]
    - rctmp_pyside.patch         [not (osx or ppc64le)]
    - osx-frame.patch            [osx]
    - win_library_path.patch     [win]
    - omit_pep8.patch            [win]

build:
  detect_binary_files_with_prefix: False
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pkg-config          [osx]
    - numpy x.x
    - python-dateutil
    - freetype 2.5.*
    - pyparsing
    - pytz
    - pycairo             [linux and py2k]
    - tornado
    - libpng 1.6.27
    - zlib 1.2.*          [win]
    - bzip2 1.0.*         [win]
    - pyqt                [not (osx or ppc64le)]
    - tk 8.5.*            [win]
    - cycler
    - nose
    - msinttypes          [win and py2k]
  run:
    - python
    - numpy x.x
    - python-dateutil
    - freetype 2.5.*      [unix]
    - pytz
    - pyparsing
    - pycairo             [linux and py2k]
    - pyqt 5.*            [not ppc64le]
    - zlib 1.2.*          [win]
    - tk 8.5.*            [win]
    - libpng >=1.6.27,<1.7
    - cycler >=0.10.0
    - functools32         [py2k]
    - subprocess32        [py2k]

test:
  requires:
    - nose
    - mock
  imports:
    - matplotlib

about:
  home: http://matplotlib.org/
  license: PSF-based
  license_url: http://matplotlib.sourceforge.net/users/license.html
  license_family: PSF
  license_file: LICENSE/LICENSE
  summary: Python 2D plotting library
  description: |
    matplotlib is a python 2D plotting library which produces publication
    quality figures in a variety of hardcopy formats and interactive
    environments across platforms. matplotlib can be used in Python scripts,
    the Python and IPython shell (ala MATLAB or Mathematica), web
    application servers, and six graphical user interface toolkits.
  doc_url: http://matplotlib.org/contents.html#
  dev_url: https://github.com/matplotlib/matplotlib
