package:
  name: boto
  version: 2.47.0

source:
  fn: boto-2.47.0.tar.gz
  url: https://pypi.python.org/packages/bc/ee/e674c01b10972765511705dc77b824b550646a30994cbc428087c4910ac3/boto-2.47.0.tar.gz
  md5: c7ed986a6f369fe93f04ec62d16299ac

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - asadmin -h     [py2k and unix]
    - s3put -h       [py2k and unix]
    - taskadmin -h   [py2k and unix]
  imports:
    - boto

about:
  home: https://github.com/boto/boto/
  license: MIT
  summary: Amazon Web Services Library
  description: |
    Boto aims to support the full breadth and depth of Amazon Web Services.
    NOTE: Boto3, the next version of Boto, is stable and recommended for
    general use.
  doc_url: http://docs.pythonboto.org/en/latest/
  doc_source_url: https://github.com/boto/boto/blob/develop/docs/source/index.rst
  dev_url: https://github.com/boto/boto/
