package:
  name: tensorflow
  version: "1.0.1"

source:
  fn: tensorflow-1.0.1.tar.gz
  url: https://github.com/tensorflow/tensorflow/archive/v1.0.1.tar.gz
  sha256: deea3c65e0703da96d9c3f1162e464c51d37659dd129396af134e9e8f1ea8c05
  patches:
    # Add -lrt to the link options list
    # https://github.com/tensorflow/tensorflow/issues/121
    - rt_link_arg.patch

build:
  number: 0
  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

requirements:
  build:
    - bazel >=0.4.5
    - numpy x.x
    - perl
    - pip
    - python
    - six >=1.10.0
    - swig
    - wheel >=0.26
    - zlib
  run:
    - mock >=2.0.0       [py2k]
    - numpy x.x
    - protobuf >=3.1.0
    - python
    - six >=1.10.0

test:
  imports:
    - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
