package:
  name: zope.deprecation
  version: 4.2.0

source:
  fn: zope.deprecation-4.2.0.tar.gz
  url: https://pypi.python.org/packages/51/85/b9d2fdcaf38ce3271ad759c7e8f0e9a28f6d900c1ad495085e4ab1de3795/zope.deprecation-4.2.0.tar.gz
  md5: 5d110c34ab7b313490c1a8533bbdc7a0

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - zope
  run:
    - python
    - zope

test:
  imports:
    - zope.deprecation

about:
  home: http://pypi.python.org/pypi/zope.deprecation
  license: ZPL 2.1
  license_family: Other
  license_file: LICENSE.txt
  summary: Zope Deprecation Infrastructure
  description: |
    Provides a simple function called deprecated(names, reason) to mark
    deprecated modules, classes, functions, methods and properties.
  doc_url: http://docs.zope.org/zope.deprecation/
  doc_source_url: https://github.com/zopefoundation/zope.deprecation//blob/master/docs/index.rst
  dev_url: https://github.com/zopefoundation/zope.deprecation
