package:
  name: scipy
  version: 0.19.0

source:
  fn: scipy-0.19.0.zip
  url: https://pypi.python.org/packages/e5/93/9a8290e7eb5d4f7cb53b9a7ad7b92b9827ecceaddfd04c2a83f195d8767d/scipy-0.19.0.zip
  md5: 91b8396231eec780222a57703d3ec550

build:
  number: 0
  detect_binary_files_with_prefix: False
  ignore_prefix_files: True   [win]
  features:
    - nomkl                   [x86 and nomkl]

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - mkl-devel 2017.0.1      [not nomkl]
    - openblas 0.2.19         [linux and nomkl]
    - cio-bt
  run:
    - python
    - numpy x.x
    - mkl 2017.0.*            [not nomkl]
    - openblas 0.2.19         [linux and nomkl]
    - libgfortran 3.0.0       [linux and not ppc64le]
    - vs2015_runtime          [win and py35]
    - vs2010_runtime          [win and py34]
    - vs2008_runtime          [win and py27]

test:
  requires:
    - nose
    - cio-bt
  imports:
    - scipy

about:
  home: http://www.scipy.org/
  license: BSD
  license_file: LICENSE.txt
  summary: Scientific Library for Python
  description: |
    SciPy is a collection of mathematical algorithms and convenience functions
    built on the Numpy extension of Python.
  doc_url: https://docs.scipy.org/doc/scipy/reference/
  doc_source_url: https://github.com/scipy/scipy/blob/master/doc/source/index.rst
  dev_url: https://github.com/scipy/scipy
