package:
  name: isort
  version: 4.2.14

source:
  fn: isort-4.2.14.tar.gz
  url: https://pypi.python.org/packages/11/70/0fcf646c3f3a524d1bd2b445c73e9e8396db708f13d144de94b395656d7f/isort-4.2.14.tar.gz
  md5: 555938e24911062b2febab248b419788

build:
  entry_points:
    - isort = isort.main:main

requirements:
  build:
    - python
  run:
    - python
    - setuptools

test:
  commands:
    - isort --help
  imports:
    - isort

about:
  home: https://github.com/timothycrosley/isort
  license: MIT
  license_file: LICENSE
  summary: Python utility / library to sort Python imports
  description: |
    isort sort imports alphabetically and automatically separated into sections.
    It provides a command line utility, library and plugins for various editors
    to quickly sort all your imports.
  doc_url: https://pypi.python.org/pypi/isort/4.2.9
  doc_source_url: https://github.com/timothycrosley/isort/blob/develop/README.rst
