package:
  name: sqlalchemy
  version: 1.1.10

source:
  fn: SQLAlchemy-1.1.10.tar.gz
  url: https://pypi.python.org/packages/a7/8c/cc24b9794ffa87506aedf528ba3a236e11cc537f81a1e3b52193e5e948cd/SQLAlchemy-1.1.10.tar.gz
  md5: 64b9a3bf34e17944f844cbf460bd14e6

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - sqlalchemy
    - sqlalchemy.cprocessors
    - sqlalchemy.cresultproxy
    - sqlalchemy.cutils

about:
  home: http://www.sqlalchemy.org/
  license: MIT
  license_file: LICENSE
  summary: Python SQL toolkit and Object Relational Mapper
  description: |
    SQLAlchemy provides a full suite of well known enterprise-level persistence
    patterns, designed for efficient and high-performing database access,
    adapted into a simple and Pythonic domain language.
  doc_url: http://docs.sqlalchemy.org/en/rel_1_0/
  doc_source_url: https://github.com/zzzeek/sqlalchemy/blob/master/doc/build/index.rst
  dev_url: https://bitbucket.org/zzzeek/sqlalchemy/
