package:
  name: sqlalchemy
  version: 1.1.11

source:
  fn: SQLAlchemy-1.1.11.tar.gz
  url: https://pypi.python.org/packages/59/f1/28f2205c3175e6bf32300c0f30f9d91dbc9eb910debbff3ffecb88d18528/SQLAlchemy-1.1.11.tar.gz
  md5: 3de387eddb4012083a4562928c511e43

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - sqlalchemy
    - sqlalchemy.cprocessors
    - sqlalchemy.cresultproxy
    - sqlalchemy.cutils

about:
  home: http://www.sqlalchemy.org/
  license: MIT
  license_file: LICENSE
  summary: Python SQL toolkit and Object Relational Mapper
  description: |
    SQLAlchemy provides a full suite of well known enterprise-level persistence
    patterns, designed for efficient and high-performing database access,
    adapted into a simple and Pythonic domain language.
  doc_url: http://docs.sqlalchemy.org/en/rel_1_0/
  doc_source_url: https://github.com/zzzeek/sqlalchemy/blob/master/doc/build/index.rst
  dev_url: https://bitbucket.org/zzzeek/sqlalchemy/
