package:
  name: scipy
  version: 0.18.1

source:
  fn: scipy-0.18.1.tar.gz
  url: https://pypi.python.org/packages/22/41/b1538a75309ae4913cdbbdc8d1cc54cae6d37981d2759532c1aa37a41121/scipy-0.18.1.tar.gz
  md5: 5fb5fb7ccb113ab3a039702b6c2f3327

build:
  number: 0
  ignore_prefix_files: True   [win]
  features:
    - nomkl                   [nomkl]

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - mkl-devel 11.3.3        [not nomkl]
    - openblas 0.2.14         [linux and nomkl and (not ppc64le)]
    - cio-bt                  [unix]
  run:
    - python
    - numpy x.x
    - mkl 11.3.3              [not nomkl]
    - openblas 0.2.14         [linux and nomkl and (not ppc64le)]
    - libgfortran 3.0.0       [linux]
    - vs2015_runtime          [win and py35]
    - vs2010_runtime          [win and py34]
    - vs2008_runtime          [win and py27]

test:
  requires:
    - nose
    - cio-bt
  imports:
    - scipy

about:
  home: http://www.scipy.org/
  license: BSD
  license_file: LICENSE.txt
  summary: Scientific Library for Python
  description: |
    SciPy is a Python-based ecosystem of open-source software for mathematics,
    science, and engineering.
  doc_url: http://www.scipy.org/docs.html
  dev_url: https://github.com/scipy/scipy
