package:
  name: python-dateutil
  version: 2.6.0

source:
  fn: python-dateutil-2.6.0.tar.gz
  url: https://pypi.python.org/packages/51/fc/39a3fbde6864942e8bb24c93663734b74e281b984d1b8c4f95d64b0c21f6/python-dateutil-2.6.0.tar.gz
  md5: 6e38f91e8c94c15a79ce22768dfeca87

requirements:
  build:
    - python
    - setuptools
    - six
  run:
    - python
    - six

test:
  imports:
    - dateutil
    - dateutil.rrule

about:
  home: https://dateutil.readthedocs.org/
  license: BSD
  license_file: LICENSE
  summary: extensions to the standard Python datetime module
  description: |
    The dateutil module provides powerful extensions to the standard datetime
    module, available in Python.
  doc_url: https://dateutil.readthedocs.org/en/latest/
  doc_source_url: https://github.com/dateutil/dateutil/blob/master/docs/index.rst
  dev_url: https://github.com/dateutil/dateutil/
