package:
  name: chardet
  version: 3.0.3

source:
  fn: chardet-3.0.3.tar.gz
  url: https://pypi.python.org/packages/fc/f9/3963ae8e196ceb4a09e0d7906f511fdf62a631f05d9288dc4905a93a1f52/chardet-3.0.3.tar.gz
  md5: d92908d1b0b61dbbd63fb18d33c6493a

build:
  entry_points:
    - chardetect = chardet.cli.chardetect:main

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python

test:
  imports:
    - chardet
  commands:
    - chardetect --help

about:
  home: https://github.com/chardet/chardet
  license: GNU Lesser General Public License
  license_family: LGPL
  license_file: LICENSE
  summary: Universal character encoding detector
  description: |
    chardet is a character encoding auto-detector in Python.
  doc_url: http://chardet.readthedocs.org/
  doc_source_url: https://github.com/chardet/chardet/blob/master/docs/index.rst
  dev_url: https://github.com/chardet/chardet
