package:
  name: gensim
  version: 2.1.0

source:
  fn: gensim-2.1.0.tar.gz
  url: https://pypi.python.org/packages/0c/35/0e2dbd6ff005d021ab89bcb35baeeff19bf7a3f30f75f98820f1d2876b39/gensim-2.1.0.tar.gz
  md5: c860c86fba481cc1b78792f87ef3c259

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
    - scipy
    - six
  run:
    - python
    - numpy x.x
    - scipy
    - six
    - smart_open

test:
  imports:
    - gensim
    - gensim.models.doc2vec_inner
    - gensim.models.word2vec_inner

about:
  home: http://radimrehurek.com/gensim
  license: GNU Lesser General Public License v2 or later
  license_family: LGPL
  license_file: COPYING
  summary: Topic Modelling in Python
  description: |
    Gensim is a free Python library designed to automatically extract semantic
    topics from documents, as efficiently (computer-wise) and painlessly (human-wise) as possible.
  doc_url: http://radimrehurek.com/gensim/tutorial.html
  doc_source_url: https://github.com/RaRe-Technologies/gensim/blob/develop/docs/src/tutorial.rst
  dev_url: https://github.com/piskvorky/gensim
