package:
  name: gensim
  version: 2.2.0

source:
  fn: gensim-2.2.0.tar.gz
  url: https://pypi.python.org/packages/fe/66/81322796cb00b5ce9ad7e12a89f57879125c5c64539dbb84c413a3c518ea/gensim-2.2.0.tar.gz
  md5: 5655142e7df7f33fe1f484df82c35d64

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
    - scipy
    - six
  run:
    - python
    - numpy x.x
    - scipy >=0.19.0
    - six
    - smart_open >=1.2.1

test:
  imports:
    - gensim
    - gensim.models.doc2vec_inner
    - gensim.models.word2vec_inner

about:
  home: http://radimrehurek.com/gensim
  license: GNU Lesser General Public License v2 or later
  license_family: LGPL
  license_file: COPYING
  summary: Topic Modelling in Python
  description: |
    Gensim is a free Python library designed to automatically extract semantic
    topics from documents, as efficiently (computer-wise) and painlessly (human-wise) as possible.
  doc_url: http://radimrehurek.com/gensim/tutorial.html
  doc_source_url: https://github.com/RaRe-Technologies/gensim/blob/develop/docs/src/tutorial.rst
  dev_url: https://github.com/piskvorky/gensim
