package:
  name: sphinx
  version: 1.6.2

source:
  fn: Sphinx-1.6.2.tar.gz
  url: https://pypi.python.org/packages/72/68/ad424cd0caf5ea9d3b53b0ed5653eb09c4abde99b0c0ec84141935281775/Sphinx-1.6.2.tar.gz
  md5: a5f613e2b807c1f8c6cdd985a3d909f1

build:
  entry_points:
    - sphinx-build = sphinx:main
    - sphinx-quickstart = sphinx.quickstart:main
    - sphinx-apidoc = sphinx.apidoc:main
    - sphinx-autogen = sphinx.ext.autosummary.generate:main
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - six
    - jinja2
    - pygments
    - docutils
    - snowballstemmer
    - babel
    - alabaster
    - sphinx_rtd_theme
    - imagesize
    - requests
    - sphinxcontrib-websupport
    - typing                        [py < 35]
    - colorama                      [win]
  run:
    - python
    - six
    - jinja2
    - pygments >=2.0
    - docutils >=0.11
    - snowballstemmer >=1.1
    - babel >=1.3,!=2.0
    - alabaster >=0.7,<0.8
    - imagesize
    - requests >=2.0.0
    - sphinxcontrib-websupport
    - typing                        [py < 35]
    - colorama >=0.3.5              [win]

test:
  commands:
    - sphinx-build -h
    - sphinx-quickstart -h
    - sphinx-apidoc -h
    - sphinx-autogen -h
  imports:
    - sphinx
    - sphinx.pycode

about:
  home: http://sphinx-doc.org
  license: BSD
  license_file: LICENSE
  summary: Documentation generator
  description: |
    Sphinx is a tool that makes it easy to create intelligent and beautiful
    documentation.
  doc_url: http://www.sphinx-doc.org/en/stable/contents.html
  doc_source_url: https://github.com/sphinx-doc/sphinx/blob/master/doc/contents.rst
  dev_url: https://github.com/sphinx-doc/sphinx/
