package:
  name: pycparser
  version: 2.17

source:
  fn: pycparser-2.17.tar.gz
  url: https://pypi.python.org/packages/be/64/1bb257ffb17d01f4a38d7ce686809a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz
  md5: ca98dcb50bc1276f230118f6af5a40c7

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - pycparser

about:
  home: https://github.com/eliben/pycparser
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: C parser in Python
  description: |
    pycparser is written in pure Python using the PLY parsing library.
    It parses C code into an AST and can serve as a front-end for C compilers
    or analysis tools.
  doc_url: https://pypi.python.org/pypi/pycparser
  doc_source_url: https://github.com/eliben/pycparser
