package:
  name: xlwings
  version: 0.10.4

source:
  fn: xlwings-0.10.4.tar.gz
  url: https://pypi.python.org/packages/13/c8/c9a3b0108793cc6afe4505a6c50326e9b3989d50502079e44f48e7303ebf/xlwings-0.10.4.tar.gz
  md5: 5c8e18b4a09e99cfffb27e9f70633969

build:
  entry_points:
    - xlwings = xlwings.command_line:main

requirements:
  build:
    - python
  run:
    - python
    - pytz
    - comtypes             [win]
    - pywin32              [win]
    - psutil >=2.0         [osx]
    - appscript >=1.0.1    [osx]

test:
  commands:
    - xlwings -h           [win]
  imports:
    - xlwings

about:
  home: http://xlwings.org/
  license: 3-clause BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Interact with Excel from Python and vice versa
  description: |
     xlwings is a BSD-licensed Python library that makes it easy to call Python from Excel and vice versa.
  doc_url: http://docs.xlwings.org/en/stable/index.html
  doc_source_url: https://github.com/ZoomerAnalytics/xlwings/blob/4f6801bba410df7483102d287af41ca92c84d3a2/docs/quickstart.rst
  dev_url: https://github.com/ZoomerAnalytics/xlwings
