package:
  name: pytest
  version: 3.1.1

source:
  fn: pytest-3.1.1.tar.gz
  url: https://pypi.python.org/packages/96/51/8fa6bdb9c80e21a90e162f6774da2506497ef0c92afae8ba654c3a5ce4c3/pytest-3.1.1.tar.gz
  md5: dfb110518cacc5b26ec5dd79877feb16

build:
  entry_points:
    - pytest = pytest:main
    - py.test = pytest:main

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - py
    - colorama          [win]
  run:
    - python
    - setuptools
    - py >=1.4.29
    - colorama          [win]

test:
  commands:
    - pytest -h
    - py.test -h
  imports:
    - pytest

about:
  home: http://pytest.org/
  license: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org/en/latest/contents.html#toc
  doc_source_url: https://github.com/pytest-dev/pytest/blob/master/doc/en/contents.rst
  dev_url: https://github.com/pytest-dev/pytest/
