package:
  name: pytest
  version: 3.1.2

source:
  fn: pytest-3.1.2.tar.gz
  url: https://pypi.python.org/packages/72/2b/2d3155e01f45a5a04427857352ee88220ee39550b2bc078f9db3190aea46/pytest-3.1.2.tar.gz
  md5: c4d179f89043cc925e1c169d03128e02

build:
  entry_points:
    - pytest = pytest:main
    - py.test = pytest:main

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - py
    - colorama          [win]
  run:
    - python
    - setuptools
    - py >=1.4.33
    - colorama          [win]

test:
  commands:
    - pytest -h
    - py.test -h
  imports:
    - pytest

about:
  home: http://pytest.org/
  license: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org/en/latest/contents.html#toc
  doc_source_url: https://github.com/pytest-dev/pytest/blob/master/doc/en/contents.rst
  dev_url: https://github.com/pytest-dev/pytest/
