package:
  name: pytest
  version: 3.1.3

source:
  fn: pytest-3.1.3.tar.gz
  url: https://pypi.python.org/packages/15/c8/6b42bf58f91d72416806472512bb67dabc6edb5a6a8ace29853ff940400a/pytest-3.1.3.tar.gz
  md5: 35356e6e31cbd8318e8b2a8340a90b72

build:
  entry_points:
    - pytest = pytest:main
    - py.test = pytest:main

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - py
    - colorama          [win]
  run:
    - python
    - setuptools
    - py >=1.4.33
    - colorama          [win]

test:
  commands:
    - pytest -h
    - py.test -h
  imports:
    - pytest

about:
  home: http://pytest.org/
  license: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org/en/latest/contents.html#toc
  doc_source_url: https://github.com/pytest-dev/pytest/blob/master/doc/en/contents.rst
  dev_url: https://github.com/pytest-dev/pytest/
