package:
  name: tqdm
  version: 4.14.0

source:
  fn: tqdm-4.14.0.tar.gz
  url: https://pypi.python.org/packages/67/7c/95e5425871bf314e484aea5f8ec65b49ab006944309b496cd53c47646155/tqdm-4.14.0.tar.gz
  md5: 132f85f0f2ffad4226a2156b9b100653

build:
  entry_points:
    - tqdm=tqdm._main:main
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - tqdm
  commands:
    - tqdm --help
    - tqdm -v

about:
  home: https://github.com/tqdm/tqdm
  license: MPLv2.0, MIT
  license_family: MIT
  license_file: LICENCE
  summary: a fast, extensible progress meter
