package:
  name: distributed
  version: 1.16.3

source:
  fn: distributed-1.16.3.tar.gz
  url: https://pypi.python.org/packages/5d/88/8ca90404213c1023902b37a60bd83f8a391e4823bca8675c72ee34df17fb/distributed-1.16.3.tar.gz
  md5: 45a156973f234c3c77cc970b3371a47c

build:
  number: 0
  entry_points:
    - dask-ssh=distributed.cli.dask_ssh:go
    - dask-submit=distributed.cli.dask_submit:go
    - dask-remote=distributed.cli.dask_remote:go
    - dask-scheduler=distributed.cli.dask_scheduler:go
    - dask-worker=distributed.cli.dask_worker:go

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - tornado >=4.2
    - toolz >=0.7.4
    - msgpack-python
    - cloudpickle >=0.2.2
    - dask >=0.14.1
    - click >=6.6
    - six
    - tblib
    - psutil
    - zict >=0.1.1
    - sortedcollections
    - futures                     [py < 30]
    - singledispatch              [py < 34]

test:
  commands:
    - dask-ssh --help
    - dask-scheduler --help
    - dask-worker --help
  imports:
    - distributed
    - distributed.bokeh
    - distributed.bokeh.status
    - distributed.bokeh.tasks
    - distributed.cli
    - distributed.diagnostics
    - distributed.http

about:
  home: http://distributed.readthedocs.org/en/latest/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Lightweight library for distributed computing in Python
  description: |
    Distributed is a lightweight library for distributed computing in Python.
    It extends both the concurrent.futures and dask APIs to moderate sized
    clusters.  Distributed provides data-local computation by keeping data on
    worker nodes, running computations where data lives, and by managing
    complex data dependencies between tasks.
  doc_url: http://distributed.readthedocs.org
  dev_url: https://github.com/dask/distributed
