package:
  name: zlib
  version: 1.2.8

source:
  fn: zlib-1.2.8.tar.gz
  url: http://pkgs.fedoraproject.org/repo/pkgs/mingw-zlib/zlib-1.2.8.tar.gz/44d667c142d7cda120332623eab69f40/zlib-1.2.8.tar.gz
  md5: 44d667c142d7cda120332623eab69f40

build:
  number: 3
  features:
    - vc9        [win and py27]
    - vc10       [win and py34]
    - vc14       [win and (py35 or py36)]

requirements:
  build:
    - cmake      [win]

about:
  home: http://zlib.net/
  license: zlib
  license_url: http://zlib.net/zlib_license.html
  license_family: Other
  summary: Unobtrusive compression library
  description: |
    The zlib compression library provides in-memory compression and decompression
    functions, including integrity checks of the uncompressed data.
  doc_url: http://zlib.net/manual.html
  doc_source_url: https://github.com/madler/zlib/tree/master/doc
  dev_url: https://github.com/madler/zlib
