package:
  name: pyflakes
  version: 1.5.0

source:
  fn: pyflakes-1.5.0.tar.gz
  url: https://pypi.python.org/packages/5b/b7/dcd6ebc826065ca4ccd2406aac4378e1df6eb91124625d45d520219932a1/pyflakes-1.5.0.tar.gz
  md5: 84a99f05e5409f8196325dda3f5a1b9a

build:
  entry_points:
    - pyflakes = pyflakes.api:main

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - pyflakes test_file.py      [not (win and py3k)]
    - pyflakes --version
  files:
    - test_file.py
  imports:
    - pyflakes

about:
  home: https://launchpad.net/pyflakes
  license: MIT
  license_file: LICENSE
  summary: passive checker of Python programs
  description: |
    Pyflakes analyzes programs and detects various errors. It works by parsing
    the source file, not importing it, so it is safe to use on modules with side
    effects. It is also much faster.
  doc_url: https://pypi.python.org/pypi/pyflakes
  doc_source_url: https://github.com/PyCQA/pyflakes/blob/master/README.rst
  dev_url: https://github.com/pyflakes/pyflakes
