package:
  name: wrapt
  version: 1.10.10

source:
  fn: wrapt-1.10.10.tar.gz
  url: https://pypi.python.org/packages/a3/bb/525e9de0a220060394f4aa34fdf6200853581803d92714ae41fc3556e7d7/wrapt-1.10.10.tar.gz
  md5: 97365e906afa8b431f266866ec4e2e18

build:
  detect_binary_files_with_prefix: False

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - wrapt
    - wrapt._wrappers

about:
  home: https://github.com/GrahamDumpleton/wrapt
  license: BSD
  license_file: LICENSE
  summary: Module for decorators, wrappers and monkey patching
  description: |
    The aim of the wrapt module is to provide a transparent object proxy for Python, which can be used as the basis for the construction of function
    wrappers and decorator functions.
  doc_url: http://wrapt.readthedocs.org/en/latest/
  doc_source_url: https://github.com/GrahamDumpleton/wrapt/blob/master/docs/index.rst
  dev_url: https://github.com/GrahamDumpleton/wrapt
